#! /bin/sh
workspace=`pwd`
cd ..
dirc=`pwd`
cd $workspace

libs="$dirc/common:$dirc/libs:$dirc/master:$dirc/slave:."
export PYTHONPATH="$libs"
nosetests -sv -w . --nologcapture --nocapture --with-ThreadsAlive
#> /tmp/execution 2>&1
#--with-cov --cov ../master/ --cov ../slave/ --cov ../common

#nosetests -sv BusinessLogic/Execution/TestExecutionIntegrationExec2.py --nologcapture --nocapture --with-ThreadsAlive
#tests.TestNetwork.TestNetworkIntegrationExec2
#nosetests -sv TestNetwork/TestNetworkIntegrationExec.py --nologcapture --nocapture --with-ThreadsAlive
